In [30]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6]])

print(x.shape)
print(x.ndim)

(2, 3)
2


In [31]:
# 벡터의 내적 (1차원 * 1차원)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.dot(a, b))
print(np.matmul(a, b))
print(a @ b)

32
32
32


In [32]:
# 행렬의 곱 (2차원 * 2차원)
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(np.dot(a, b))
print(np.matmul(a, b))
print(a @ b)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [33]:
# 행렬의 곱 (2차원 * 1차원)
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])

print(np.dot(a, b))
print(np.matmul(a, b))
print(a @ b)

print(np.dot(b, a))
print(np.matmul(b, a))
print(b @ a)

[17 39]
[17 39]
[17 39]
[23 34]
[23 34]
[23 34]


In [34]:
# 행렬 * 스칼라
a = np.array([[1, 2], [3, 4]])
b = 2

print(a * b)
print(np.dot(a, b))
print(np.matmul(a, b)) # 오류 발생
print(a @ b) # 오류 발생

[[2 4]
 [6 8]]
[[2 4]
 [6 8]]


ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [35]:
# 3차원 이상 행렬 곱
a = np.ones([5, 7, 4, 3])
b = np.ones([5, 7, 3, 6])

print(np.dot(a, b).shape)
print(np.matmul(a, b).shape)
print((a @ b).shape)

(5, 7, 4, 5, 7, 6)
(5, 7, 4, 6)
(5, 7, 4, 6)
